# Generated by Django 4.2.3 on 2023-07-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_id',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
