# Generated by Django 4.2.6 on 2025-01-29 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0002_media_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='youtube_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 14, 30, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
