# Generated by Django 4.2.6 on 2025-02-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0003_media_youtube_upload_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='media',
            name='category',
        ),
        migrations.AddField(
            model_name='channel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='channels', to='subplayer.category'),
        ),
        migrations.AddField(
            model_name='media',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='media', to='subplayer.category'),
        ),
    ]
