# Generated by Django 4.2.3 on 2023-07-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0003_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='end_time',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='start_time',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
