# Generated by Django 4.2.6 on 2025-11-03 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subplayer', '0004_category_remove_media_category_channel_categories_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='highlight',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='highlight',
            name='source',
            field=models.CharField(choices=[('media', 'Media'), ('chat', 'Chat')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='end_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='end_sentence_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='end_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='frame_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='subplayer.media'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='start_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='start_sentence_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='start_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='highlight',
            unique_together={('user', 'source', 'media', 'start_time', 'end_time', 'highlighted_text')},
        ),
    ]
