# Generated by Django 4.2.6 on 2025-11-08 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0005_alter_highlight_unique_together_highlight_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='highlight',
            name='source',
            field=models.CharField(choices=[('media', 'Media'), ('chat', 'Chat'), ('web', 'Web')], default='media', max_length=10),
        ),
    ]
