# Generated by Django 4.2.3 on 2023-07-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0005_highlight_end_index_highlight_end_sentence_index_and_more'),
    ]

    operations = [
    ]
