# Generated by Django 4.2.6 on 2025-11-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0006_article_alter_highlight_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='page_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='page_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
