# Generated by Django 4.2.6 on 2025-12-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_mediaprogress_minutes_watched_and_more'),
        ('subplayer', '0006_article_content_article_description_article_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='end_index',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='end_sentence_index',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='frame_index',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='start_index',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='start_sentence_index',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='start_time',
        ),
        migrations.AddField(
            model_name='highlight',
            name='chat_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_highlights', to='accounts.chatsession'),
        ),
    ]
