# Generated by Django 4.2.3 on 2023-07-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0006_auto_20230723_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='end_index',
            field=models.IntegerField(),
        ),
    ]
