# Generated by Django 4.2.6 on 2025-12-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0007_remove_highlight_end_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='end_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='end_sentence_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='end_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='frame_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='start_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='start_sentence_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='start_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='source',
            field=models.CharField(choices=[('media', 'Media'), ('chat', 'Chat'), ('web', 'Web')], max_length=10),
        ),
    ]
