# Generated by Django 4.2.6 on 2026-01-11 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_chatcategory_chatsession_category'),
        ('subplayer', '0008_highlight_end_index_highlight_end_sentence_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='chat_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='accounts.chatmessage'),
        ),
    ]
