# Generated by Django 4.2.6 on 2025-11-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0009_article_created_by_article_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlehighlight',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='subplayer.article'),
        ),
    ]
