# Generated by Django 4.2.6 on 2026-01-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0009_highlight_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='subplayer.article'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='source',
            field=models.CharField(choices=[('media', 'Media'), ('chat', 'Chat'), ('web', 'Web'), ('read', 'Read')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['user', 'source', 'created_at'], name='subplayer_h_user_id_ccf4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['user', 'page_url'], name='subplayer_h_user_id_a7e1db_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['user', 'article'], name='subplayer_h_user_id_df7e09_idx'),
        ),
    ]
