# Generated by Django 4.2.6 on 2024-02-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0010_alter_media_sentences_alter_media_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('audio', 'Audio')], max_length=10, null=True),
        ),
    ]
