# Generated by Django 4.2.6 on 2025-11-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0010_articlehighlight_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
