# Generated by Django 4.2.6 on 2026-01-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0010_article_content_html_highlight_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='source',
            field=models.CharField(choices=[('media', 'Media'), ('chat', 'Chat'), ('web', 'Web'), ('read', 'Read')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_by', 'created_at'], name='subplayer_a_created_8df1b9_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_by', 'source_url'], name='subplayer_a_created_81a4b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('created_by', 'source_url'), name='uniq_user_source_url'),
        ),
    ]
