# Generated by Django 4.2.6 on 2024-02-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0011_media_subtitle_file_alter_media_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
