# Generated by Django 4.2.6 on 2024-02-09 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subplayer', '0012_media_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='users',
            field=models.ManyToManyField(related_name='added_media', to=settings.AUTH_USER_MODEL),
        ),
    ]
