# Generated by Django 4.2.6 on 2024-02-17 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subplayer', '0014_media_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMediaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='subplayer.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'media')},
            },
        ),
    ]
