# Generated by Django 4.2.6 on 2024-03-26 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0016_media_video_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermediastatus',
            name='completion_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
