# Generated by Django 4.2.6 on 2024-03-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0017_usermediastatus_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='number_words',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
