# Generated by Django 4.2.6 on 2024-05-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0022_alter_media_video_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
