# Generated by Django 4.2.6 on 2024-05-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0023_media_profile_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='category',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='subplayer.channel'),
            preserve_default=False,
        ),
    ]
