# Generated by Django 4.2.6 on 2024-03-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_word_count',
            field=models.IntegerField(default=0, help_text='Total word count from completed videos.'),
        ),
    ]
