# Generated by Django 4.2.6 on 2024-03-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_total_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_highlights',
            field=models.IntegerField(default=0, help_text='Total highlights'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_minutes',
            field=models.IntegerField(default=0, help_text='Total minutes of video completed'),
        ),
    ]
