# Generated by Django 4.2.6 on 2024-04-05 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0022_alter_media_video_length'),
        ('accounts', '0003_profile_total_highlights_profile_total_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaprogress',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mediaprogress',
            name='minutes_watched',
            field=models.IntegerField(default=0, help_text='Number of minutes watched during this session.'),
        ),
        migrations.AddField(
            model_name='mediaprogress',
            name='words_learned',
            field=models.IntegerField(default=0, help_text='Number of words learned during this session.'),
        ),
        migrations.AlterUniqueTogether(
            name='mediaprogress',
            unique_together={('media', 'profile', 'date')},
        ),
    ]
