# Generated by Django 4.2.6 on 2024-05-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mediaprogress_date_mediaprogress_minutes_watched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_points',
            field=models.IntegerField(default=0, help_text='Total points accumulated'),
        ),
    ]
