# Generated by Django 4.2.6 on 2025-03-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0004_category_remove_media_category_channel_categories_and_more'),
        ('accounts', '0005_subscription_next_billing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribed_channels',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='subplayer.channel'),
        ),
    ]
