# Generated by Django 4.2.6 on 2025-12-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaprogress',
            name='minutes_watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediaprogress',
            name='words_learned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_highlights',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
