# Generated by Django 4.2.6 on 2024-06-14 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subplayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stopped', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('words_learned', models.IntegerField(default=0, help_text='Number of words learned during this session.')),
                ('minutes_watched', models.IntegerField(default=0, help_text='Number of minutes watched during this session.')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subplayer.media')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_word_count', models.IntegerField(default=0, help_text='Total word count from completed videos.')),
                ('total_minutes', models.IntegerField(default=0, help_text='Total minutes of video completed')),
                ('total_highlights', models.IntegerField(default=0, help_text='Total highlights')),
                ('total_points', models.IntegerField(default=0, help_text='Total points accumulated')),
                ('finished_media', models.ManyToManyField(blank=True, related_name='finished_users', to='subplayer.media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewed_media', models.ManyToManyField(blank=True, related_name='viewing_users', through='accounts.MediaProgress', to='subplayer.media')),
            ],
        ),
        migrations.AddField(
            model_name='mediaprogress',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='mediaprogress',
            unique_together={('media', 'profile', 'date')},
        ),
    ]
