# Generated by Django 4.2.6 on 2024-06-14 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('profile_pic_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(blank=True, choices=[('video', 'Video'), ('audio', 'Audio')], max_length=10, null=True)),
                ('url', models.URLField()),
                ('sentences', models.JSONField(blank=True, null=True)),
                ('words', models.JSONField(blank=True, null=True)),
                ('media_id', models.CharField(max_length=200)),
                ('subtitle_file', models.FileField(blank=True, null=True, upload_to='subtitles/')),
                ('youtube_video_id', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('video_length', models.PositiveIntegerField(blank=True, help_text='Length of the video in seconds.', null=True)),
                ('word_count', models.IntegerField(blank=True, default=0, help_text='Estimated word count from video subtitles.', null=True)),
                ('category', models.CharField(default='Unknown', max_length=255)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='subplayer.channel')),
                ('users', models.ManyToManyField(related_name='added_media', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMediaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='subplayer.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'media')},
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('end_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('highlighted_text', models.TextField()),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('start_sentence_index', models.IntegerField()),
                ('end_sentence_index', models.IntegerField()),
                ('frame_index', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='subplayer.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'media', 'start_time', 'end_time', 'highlighted_text')},
            },
        ),
    ]
