# Generated by Django 4.2.3 on 2023-07-23 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subplayer', '0007_alter_highlight_end_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='highlight',
            unique_together={('user', 'media', 'start_time', 'end_time', 'highlighted_text')},
        ),
    ]
