# Generated by Django 4.2.3 on 2023-07-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0008_alter_highlight_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='frame_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
