# Generated by Django 4.2.6 on 2024-02-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0009_highlight_frame_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='sentences',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='words',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
