# Generated by Django 4.2.6 on 2024-02-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0013_media_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
