# Generated by Django 4.2.6 on 2024-03-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0015_usermediastatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='video_length',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
