# Generated by Django 4.2.6 on 2024-03-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0018_media_number_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='number_words',
        ),
        migrations.AddField(
            model_name='media',
            name='word_count',
            field=models.IntegerField(blank=True, default=0, help_text='Estimated word count from video subtitles.', null=True),
        ),
    ]
