# Generated by Django 4.2.6 on 2024-03-30 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0019_remove_media_number_words_media_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
