# Generated by Django 4.2.6 on 2024-03-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0021_alter_usermediastatus_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='video_length',
            field=models.PositiveIntegerField(blank=True, help_text='Length of the video in seconds.', null=True),
        ),
    ]
