# Generated by Django 4.2.6 on 2024-05-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplayer', '0024_channel_media_category_media_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='profile_pic_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
